# Generated by Django 3.2.8 on 2022-10-11 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('content', models.CharField(max_length=5000)),
                ('createted_at', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 16, 56, 57, 219915, tzinfo=utc))),
                ('image', models.ImageField(upload_to='post-image/')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
